name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Backend Image
    - name: Build Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/feedback-backend:latest ./backend

    # Build Frontend Image
    - name: Build Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/feedback-frontend:latest ./frontend

    # Push Backend Image
    - name: Push Backend Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/feedback-backend:latest

    # Push Frontend Image
    - name: Push Frontend Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/feedback-frontend:latest

    # Deploy to Kubernetes
    - name: Set up kubectl
      uses: azure/setup-kubectl@v4

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f frontend-deployment.yaml